# https://taskfile.dev

version: "3"

vars:
  GREETING: Hello, World!

tasks:
  build-ui:
    dir: ./src/ui
    cmds:
      - npx shadow-cljs release app
      - rm -rf ../mooshroom/resources/public
      - cp -r public ../mooshroom/resources/public

includes:
  local:
    taskfile: deploy/local
    dir: deploy/local
  backend:
    taskfile: ./src/mooshroom
    dir: ./src/mooshroom
  web:
    taskfile: ./src/ui
    dir: ./src/ui
