# https://taskfile.dev

version: "3"

vars:
  GREETING: Hello, World!

tasks:
  default:
    cmds:
      - echo "{{.GREETING}}"
    silent: true

includes:
  local:
    taskfile: deploy/local
    dir: deploy/local
  backend:
    taskfile: ./src/mooshroom
    dir: ./src/mooshroom
  web:
    taskfile: ./src/ui
    dir: ./src/ui
