services:
  postgres:
    image: timescale/timescaledb:latest-pg18
    ports:
      - 15432:5432
    environment:
      POSTGRES_PASSWORD: postgres
  nats:
    image: nats:latest
    command: "-c /nats.conf"
    volumes:
      - ./nats.conf:/nats.conf
    ports:
      - 11883:1883
