# https://taskfile.dev

version: "3"

vars:
  GREETING: Hello, World!

tasks:
  up:
    cmds:
      - docker-compose up -d
      - goose up
  down:
    cmds:
      - goose down
      - docker-compose stop
  caddy:
    cmds:
      - caddy run --config Caddyfile
  reset:
    cmds:
      - docker-compose down
  sim-spore:
    dir: ../..
    cmds:
      - ./mooshroom tools spore-sim -c deploy/local/config.yaml
  backend:
    dir: ../..
    cmds:
      - ./mooshroom server -c deploy/local/config.yaml
  psql:
    env:
      PGPASSWORD: postgres
    cmds:
      - psql -h localhost -U postgres -p 15432
