# https://taskfile.dev

version: "3"

vars:
  GREETING: Hello, World!

tasks:
  dev:
    cmds:
      - npm install
      - npx shadow-cljs watch app
  build:
    cmds:
      - npx shadow-cljs release app
      - rm -rf ../internal/ui/public
      - cp -r public ../internal/ui
